#!/usr/bin/python3
import os

fs = os.walk('.')

for root, dirs, files in fs:
    if root == '.':
        files.remove('README.md')
        files.remove('install')
        files.remove('installsh')
    if '.git' in dirs:
        dirs.remove('.git')
    for f in files:
        dest_path = os.path.join(os.getenv('HOME'), root)
        if os.path.exists(os.path.join(dest_path, f)):
            os.remove(os.path.join(dest_path, f))
        os.makedirs(dest_path, exist_ok=True)
        os.link(os.path.join(root, f), os.path.join(dest_path, f))
