#!/bin/env bash

for FNAME in $(git ls-files)
do
    if [[ $FNAME != README.md && $FNAME != install && $FNAME != installsh ]]; then
	parentdir="$(dirname "$HOME/$FNAME")"
        if [[ ! -f "$parentdir" ]]; then
		mkdir -p $parentdir
        fi
        cp -fl $FNAME ~/$FNAME
    fi
done
