#!/bin/env bash

for FNAME in $(git ls-files)
do
    if [[ $FNAME != README.md && $FNAME != install && $FNAME != installsh ]]; then
        if [[ $1 == "-i" ]]; then
            cp -il $FNAME ~/$FNAME
        else
            cp -l $FNAME ~/$FNAME
        fi
    fi
done


